# Generated by Django 3.1.1 on 2021-02-17 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (0, 'Sunday')])),
                ('group', models.IntegerField(choices=[(1, '8А'), (2, '8Б'), (4, '9А'), (5, '9Б'), (3, '9В'), (11, '9Г'), (9, '9Е'), (12, '10А'), (13, '10Б'), (14, '10В'), (15, '10Г'), (16, '10Д'), (17, '10Е'), (18, '10З'), (19, '10К'), (20, '10Л'), (21, '10М'), (22, '10Н'), (23, '10С'), (6, '11А'), (7, '11Б'), (8, '11В'), (24, '11Г'), (25, '11Д'), (26, '11Е'), (27, '11З'), (28, '11К'), (29, '11Л'), (30, '11М'), (32, '11Н'), (31, '11С')])),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField(choices=[(1, '8А'), (2, '8Б'), (4, '9А'), (5, '9Б'), (3, '9В'), (11, '9Г'), (9, '9Е'), (12, '10А'), (13, '10Б'), (14, '10В'), (15, '10Г'), (16, '10Д'), (17, '10Е'), (18, '10З'), (19, '10К'), (20, '10Л'), (21, '10М'), (22, '10Н'), (23, '10С'), (6, '11А'), (7, '11Б'), (8, '11В'), (24, '11Г'), (25, '11Д'), (26, '11Е'), (27, '11З'), (28, '11К'), (29, '11Л'), (30, '11М'), (32, '11Н'), (31, '11С')])),
                ('subscribers', models.ManyToManyField(related_name='subscribed_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
