# Generated by Django 3.1.1 on 2021-03-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastSchedule',
        ),
    ]
