# Generated by Django 3.1.1 on 2021-03-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_bot', '0002_delete_lastschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='chats',
            field=models.ManyToManyField(related_name='group', to='notification_bot.Chat'),
        ),
    ]
