# Generated by Django 3.1.1 on 2021-03-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_bot', '0003_auto_20210320_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='chats',
            field=models.ManyToManyField(related_name='subscribed_to', to='notification_bot.Chat'),
        ),
    ]
