# Generated by Django 3.1.6 on 2021-04-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_bot', '0004_auto_20210321_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_number',
            field=models.IntegerField(choices=[(1, '8А'), (2, '8В'), (4, '9А'), (5, '9Б'), (3, '9В'), (11, '9Г'), (9, '9Е'), (12, '10А'), (13, '10Б'), (14, '10В'), (15, '10Г'), (16, '10Д'), (17, '10Е'), (18, '10З'), (19, '10К'), (20, '10Л'), (21, '10М'), (22, '10Н'), (23, '10С'), (6, '11А'), (7, '11Б'), (8, '11В'), (24, '11Г'), (25, '11Д'), (26, '11Е'), (27, '11З'), (28, '11К'), (29, '11Л'), (30, '11М'), (32, '11Н'), (31, '11С')]),
        ),
    ]
